CREATE DATABASE wiki OWNER wikiuser;

\c wiki
GRANT ALL PRIVILEGES ON DATABASE wiki TO wikiuser;
GRANT ALL PRIVILEGES ON SCHEMA public TO wikiuser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO wikiuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO wikiuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO wikiuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO wikiuser;
