ARG BUILD_ENV_USERNAME
ARG BUILD_ENV_UID
ARG BUILD_ENV_GID 
ARG BUILD_ENV_GROUPNAME

FROM localhost/reactjs_image_root

ARG BUILD_ENV_USERNAME
ARG BUILD_ENV_UID
ARG BUILD_ENV_GID 
ARG BUILD_ENV_GROUPNAME

ENV ENV_USERNAME=$BUILD_ENV_USERNAME
ENV ENV_USER_UID=$BUILD_ENV_UID
ENV ENV_USER_GID=$BUILD_ENV_GID 
ENV ENV_USER_GROUPNAME=$BUILD_ENV_GROUPNAME

RUN echo groupadd --gid ${ENV_USER_GID} ${ENV_USERNAME}
RUN groupadd --gid ${ENV_USER_GID} ${ENV_USERNAME}
RUN echo useradd --uid ${ENV_USER_UID} --gid ${ENV_USER_GID} -m ${ENV_USERNAME}
RUN useradd --uid ${ENV_USER_UID} --gid ${ENV_USER_GID} -m ${ENV_USERNAME}

WORKDIR /usr/src/app
#COPY --from=localhost/reactjs_image_root /usr/src/app/node_modules ./node_modules
#COPY --from=localhost/reactjs_image_root /usr/src/app ./

RUN chown -R ENV_USER_UID:ENV_USER_GID /usr/src/app

RUN ls -Ral /usr/src/app

USER ENV_USER_UID:ENV_USER_GID

EXPOSE 3000
CMD ["npm", "start"]
