FROM python:3.13.1-bookworm
ARG BUILD_ENV_USERNAME
ARG BUILD_ENV_UID
ARG BUILD_ENV_GID 
ARG BUILD_ENV_GROUPNAME

ENV ENV_USERNAME=$BUILD_ENV_USERNAME
ENV ENV_UID=$BUILD_ENV_UID
ENV ENV_GID=$BUILD_ENV_GID 
ENV ENV_GROUPNAME=$BUILD_ENV_GROUPNAME

USER root

# Install system dependencies
RUN apt-get update && apt-get install -y \
    python3-dev \
    build-essential \
    libffi-dev \
    libssl-dev \
    zlib1g-dev \
    libjpeg-dev \
    libturbojpeg0-dev \
    libopenjp2-7-dev \
    libtiff-dev \
    libcurl4-openssl-dev \
    ffmpeg \
    libavformat-dev \
    libavcodec-dev \
    libavutil-dev \
    libsqlite3-dev \
    bluez \
    libbluetooth-dev \
    udev \
    libpcap-dev \
    iputils-ping \
    tzdata \
    curl \
    wget \
    libxslt-dev \
    libxml2-dev \
    mariadb-dev \
    postgresql-dev \
    libisal-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get upgrade -y

####

RUN echo groupadd --gid ${ENV_GID} ${ENV_GROUPNAME}
RUN groupadd --gid ${ENV_GID} ${ENV_GROUPNAME}
RUN echo useradd --uid ${ENV_UID} --gid ${ENV_GID} -m ${ENV_USERNAME}
RUN useradd --uid ${ENV_UID} --gid ${ENV_GID} -m ${ENV_USERNAME}

RUN mkdir /env
RUN chown -R ${ENV_UID}:${ENV_GID} /env

RUN mkdir /usr/src/homeassistant
RUN chown -R ${ENV_UID}:${ENV_GID} /usr/src/homeassistant

RUN mkdir /config
## COPY ./config/configuration.yaml /config/
RUN chown -R ${ENV_UID}:${ENV_GID} /config
RUN ls -lR /config
## the below might have been crucial?
RUN chmod -R g+rwx /config/
RUN chmod g+s /config
# RUN ls -lR /config

RUN mkdir -p /test
RUN chown -R ${ENV_UID}:${ENV_GID} /test
RUN chmod -R g+rwx /test/
RUN chmod g+s /test

