# Use the previously built Home Assistant image as the base
FROM home_assistant_image_1:latest

ARG BUILD_ENV_USERNAME
ARG BUILD_ENV_UID
ARG BUILD_ENV_GID
ARG BUILD_ENV_GROUPNAME

ENV ENV_USERNAME=$BUILD_ENV_USERNAME
ENV ENV_UID=$BUILD_ENV_UID
ENV ENV_GID=$BUILD_ENV_GID
ENV ENV_GROUPNAME=$BUILD_ENV_GROUPNAME

USER $ENV_UID:$ENV_GID

# Set working directory
WORKDIR /usr/src/homeassistant

#ENV VIRTUAL_ENV=/env
#RUN python3 -m venv $VIRTUAL_ENV
#ENV PATH="$VIRTUAL_ENV/bin:$PATH"

#RUN /env/bin/python3 -m pip install --upgrade pip
#RUN . /env/bin/activate
#RUN /env/bin/python3 --version
RUN whereis python3
RUN whereis pip3

#COPY requirements_1.txt /env/requirements_1.txt
#RUN /env/bin/pip3 install -r /env/requirements_1.txt

#RUN /env/bin/pip3 freeze

# Copy the configuration and set the correct ownership
# COPY ./config/configuration.yaml /config/

# Copy requirements and install them
# COPY requirements_2.txt /env/requirements_2.txt
# RUN /env/bin/pip3 install -r /env/requirements_2.txt


# Expose the default port used by Home Assistant
EXPOSE 8123

# Entry point remains unchanged
CMD ["hass", "--config", "/config"]
