# Use the previously built Home Assistant image as the base
FROM home_assistant_image_1:latest
ARG BUILD_ENV_USERNAME
ARG BUILD_ENV_UID
ARG BUILD_ENV_GID 
ARG BUILD_ENV_GROUPNAME

ENV ENV_USERNAME=$BUILD_ENV_USERNAME
ENV ENV_UID=$BUILD_ENV_UID
ENV ENV_GID=$BUILD_ENV_GID 
ENV ENV_GROUPNAME=$BUILD_ENV_GROUPNAME


# Set working directory
WORKDIR /usr/src/homeassistant

RUN ls -lR /config

USER ${ENV_UID}:${ENV_GID}

COPY requirements_2.txt /env/requirements_2.txt
RUN /env/bin/pip3 install -r /env/requirements_2.txt

COPY ./config/configuration.yaml /config/

RUN /env/bin/pip3 freeze

# Expose the default port used by Home Assistant
EXPOSE 8123

# Entry point remains unchanged
CMD ["/env/bin/hass", "--config", "/config"]
