FROM python:3.13.1-bookworm
ARG BUILD_ENV_USERNAME
ARG BUILD_ENV_UID
ARG BUILD_ENV_GID 
ARG BUILD_ENV_GROUPNAME

ENV ENV_USERNAME=$BUILD_ENV_USERNAME
ENV ENV_UID=$BUILD_ENV_UID
ENV ENV_GID=$BUILD_ENV_GID 
ENV ENV_GROUPNAME=$BUILD_ENV_GROUPNAME

# Install necessary system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libffi-dev \
    libssl-dev \
    libyaml-dev \
    libxml2-dev \
    libxslt1-dev \
    zlib1g-dev \
    git \
    wget \
    && apt-get clean

RUN apt-get upgrade -y

####

RUN echo groupadd --gid ${ENV_GID} ${ENV_GROUPNAME}
RUN groupadd --gid ${ENV_GID} ${ENV_GROUPNAME}
RUN echo useradd --uid ${ENV_UID} --gid ${ENV_GID} -m ${ENV_USERNAME}
RUN useradd --uid ${ENV_UID} --gid ${ENV_GID} -m ${ENV_USERNAME}

RUN mkdir /env
RUN chown -R ${ENV_UID}:${ENV_GID} /env

RUN mkdir /usr/src/homeassistant
RUN chown -R ${ENV_UID}:${ENV_GID} /usr/src/homeassistant

RUN mkdir /config
## COPY ./config/configuration.yaml /config/
RUN chown -R ${ENV_UID}:${ENV_GID} /config
RUN ls -lR /config
## the below might have been crucial?
RUN chmod -R g+rwx /config/
# RUN ls -lR /config

USER ${ENV_UID}:${ENV_GID}

ENV VIRTUAL_ENV=/env
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN /env/bin/python3 -m pip install --upgrade pip
RUN . /env/bin/activate
RUN /env/bin/python3 --version
RUN whereis python3
RUN whereis pip3

COPY requirements_1.txt /env/requirements_1.txt
RUN /env/bin/pip3 install -r /env/requirements_1.txt

RUN /env/bin/pip3 freeze


####

# Set working directory
WORKDIR /usr/src/homeassistant

# Expose the default port used by Home Assistant
# EXPOSE 8123

# Create a volume for persistent configuration
# VOLUME ["/config"]

# Set the entry point to activate the virtual environment and start Home Assistant
# CMD ["/env/bin/hass", "--config", "/config"]
